# k8s deploy.yaml where deploy name: techtrends and image: vinhloc30796/techtrends:latest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: vinhloc30796/techtrends:latest
        ports:
        - containerPort: 3111
        # liveness probe and readiness probe: :3111/healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        # resources: requests and limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"