# k8s service.yaml where namespace name: sandbox, and ClusterIP port 4111:3111
apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  ports:
    - protocol: TCP
      port: 4111
      targetPort: 3111
  type: ClusterIP
